### ISSUE TITLE
ZYTSNIP_PATH?

### ISSUE THREAD

**Issue by EpsAvlc** [sillybun/zyt-snippet#1]
您好。在用您的SNIPPET文件写latex的bmat时，发现有以下这句话。
sys.path.append(vim.eval("g:ZYTSNIP_PATH") + "UltiSnips")
因为没定义ZYTSNIP_PATH vim就会报错。请问这个有什么用呢

**Comment by sillybun** [comment]
因为我使用了自己编写的python文件，所以需要把当前python文件所在目录加入到path中，不然import就会出错。

**Comment by EpsAvlc** [comment]
python 文件可以一并上传到git仓库吗 我似乎没有在仓库中看见这个？ 谢谢！

**Comment by sillybun** [comment]
在这里呀：

https://github.com/sillybun/zyt-snippet/blob/master/UltiSnips/pythonutil.py

**Comment by EpsAvlc** [comment]
谢谢。 明白了。

**Comment by Zackhardtoname** [comment]
I'd suggest putting the file in `~/.vim/pythonx/` which gets scanned automatically by vim. In this case, we don't have to define an environment variable.

The only thing to do in the case is to make sure only .tex files it I guess.

[Source](http://vimcasts.org/episodes/ultisnips-python-interpolation/)

**Comment by ChasingZenith** [comment]
> I'd suggest putting the file in `~/.vim/pythonx/` which gets scanned automatically by vim. In this case, we don't have to define an environment variable.

I think this is a great point. I'm working on it and will make a pull request soon.

> The only thing to do in the case is to make sure only .tex files load it I guess.

This python file is not only used in latex but also used in markdown too.

**Comment by sillybun** [comment]
@Zackhardtoname @ChasingZenith this is really a good idea. Thanks a lot!
