### ISSUE TITLE
can't choose snippet class(nn)

### ISSUE THREAD

**Issue by roachsinai** [sillybun/zyt-snippet#3]
使用的[SirVer/ultisnips: UltiSnips - The ultimate snippet solution for Vim. Send pull requests to SirVer/ultisnips!](https://github.com/SirVer/ultisnips)和YouCompleteMe。

主要的问题就是repo中`python.snippets`中的python代码使得下面的配置无法使用`class(nn)`进行补全。

---

配置如下：

```
function! g:UltiSnips_Complete()
  call UltiSnips#ExpandSnippet()
  if g:ulti_expand_res == 0
    if pumvisible()
        return "\<C-n>"
    else
      call UltiSnips#JumpForwards()
      if g:ulti_jump_forwards_res == 0
        return "\<TAB>"
      endif
    endif
  endif
  return ""
endfunction

function! g:UltiSnips_Reverse()
  call UltiSnips#JumpBackwards()
  if g:ulti_jump_backwards_res == 0
    return "\<C-P>"
  endif

  return ""
endfunction

if !exists("g:UltiSnipsJumpForwardTrigger")
  let g:UltiSnipsJumpForwardTrigger = "<tab>"
endif

if !exists("g:UltiSnipsJumpBackwardTrigger")
  let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
endif

au InsertEnter * exec "inoremap <silent> " . g:UltiSnipsExpandTrigger . " <C-R>=g:UltiSnips_Complete()<cr>"
au InsertEnter * exec "inoremap <silent> " . g:UltiSnipsJumpBackwardTrigger . " <C-R>=g:UltiSnips_Reverse()<cr>"
```

上面这个配置的本意是：如果你的输入有匹配的snippet和YCM补全,直接Tab就会挑选最匹配的那个snippet。如果没有snippet能够匹配当前的输入，而有YCM补全，tab就选择下一个YCM补全。

**Comment by roachsinai** [comment]
![Screen Capture_select-area_20201019222847](https://user-images.githubusercontent.com/9500049/96464788-d3850980-125a-11eb-8ed4-2195e5c6464d.png)

如上图所示，输入`cl`会显示可以匹配的snip,如果我继续输入`nn`得到下面的结果

![Screen Capture_select-area_20201019222957](https://user-images.githubusercontent.com/9500049/96465229-4a220700-125b-11eb-9bc4-b1d0816f2748.png)

按照上面的配置，按下tab键会使用`class(nn)`补全，但是，却会继续选择下面的snip匹配（截图未列出）。

如果我把`class(nn)`这个补全复制到自己的snippets文件中则可以正确补全。

不知是不是你的python.snippets文件中的python代码的问题。

**Comment by sillybun** [comment]
我前面判断了有没有`import torch`这行代码，否则不会补全，是不是这个问题？

**Comment by roachsinai** [comment]
嗯嗯，是这个问题。感谢回复！
